# Generated by Django 4.1.6 on 2023-03-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('name', models.CharField(help_text='Customer name', max_length=50, verbose_name='Customer name')),
                ('email', models.EmailField(help_text='Customer email', max_length=254, verbose_name='Customer email')),
                ('password', models.CharField(help_text='Customer pssword', max_length=10, verbose_name='Customer password')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
